---
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Check for existing install
  ansible.builtin.stat:
    path: '{{ rustup_home }}'
  changed_when: false
  register: rustup_home_binary
- name: Downloading and installing rustup
  when: not rustup_home_binary.stat.exists
  block:
    - name: Download rustup-init...
      ansible.builtin.get_url:
        url: '{{ rustup_init_url }}'
        dest: '{{ rustup_exe }}'
        mode: '755'
    - name: Installing rust...
      ansible.builtin.command: '{{ rustup_exe }} -y'
      args:
        creates: '{{ rustup_home }}'
  always:
    - name: cleanup
      ansible.builtin.file:
        path: '{{ rustup_exe }}'
        state: absent
