---
# tasks file for rust
- name: download rust-lang...
  get_url: >
    url=https://static.rust-lang.org/rustup.sh
    dest=/tmp/rustup.sh
    mode=0755
    owner=root
    group=root

- name: install....
  command: /tmp/rustup.sh
  args:
    creates: /usr/local/bin/rustc

